export default {
  // ===== 数学基础 =====
  'shuxuefenxiB': '📐 数学分析B',
  'guanyuanshufenxi': '📐 管院数学分析',
  'xianxingdaishu': '📊 线性代数',
  'gaodengxianxingdaishu': '📈 高等线性代数',
  'gaodengdaishu': '📈 高等代数',
  'gaodengshuxueA': '📐 高等数学A',
  'gailulun': '🎲 概率论与数理统计',
  'jingyuantongjixue': '📊 经院统计学',
  'jiheyutulun': '🔗 集合与图论',
  'zuiyouhua': '📉 最优化方法',
  
  // ===== 物理化学基础 =====
  'daxuewuli': '⚡ 大学物理',
  'dianlujichu': '🔌 电路基础',
  'puhuaAshang': '🧪 普通化学A（上）',
  
  // ===== 计算机专业课 =====
  'chengxusheji': '💻 程序设计',
  'pythonchengxusheji': '🐍 Python程序设计',
  'oop': '🧩 面向对象程序设计',
  'shujujiegou': '🌲 数据结构',
  'suanfa': '⚙️ 算法设计与分析',
  'jisuanjizucheng': '🖥️ 计算机组成与体系结构',
  'shujukuyinlun': '🗄️ 数据库引论',
  'moshudianshiyan': '🔧 模数电实验',
  'rengongzhinengjichu': '🤖 人工智能基础',
  'rengongzhinengderuanjianjichu': '🤖 人工智能的软件基础',
  'daishujiegouyushuliluoji': '📚 代数结构与数理逻辑',
  'ziranyuyanchuli': '🤖 自然语言处理',

  // ===== 英语 =====
  'kejirencaiyingyugoutong': '🗣️ 科技人才英语沟通',
  // ===== 经济学 =====
  'weiguanjingjixue': '📈 微观经济学',
  'zhengzhijingjixue': '📕 政治经济学',
  
  // ===== 通识课程 =====
  'tengfeixiandao': '🚀 腾飞先导课',
  'jindaishi': '📜 近代史纲要',
  'xigai': '📕 习概',
  'makesi': '📗 马克思主义基本原理',
  'maogai': '📗 毛概',
  'songcidaodu': '📜 宋词导读',
  'fazhexueyuanlidaodu': '📚 《法哲学原理》导读',
  'gaigekaifangshi': '📚 改革开放史',
  'gailvtongjiyugongchengshuxue': '📚 概率统计与工程数学',
  'gaodengshuxueBxia': '📚 高等数学B（下）',
  'jichuwulishiyan': '📚 基础物理实验',
  'jingju': '📚 京剧',
  'junshililun': '📚 军事理论',
  'monidianziluxian': '📚 模拟电子线路',
  'qianrushichuliyuxinpixitongsheji': '📚 嵌入式处理器与芯片系统设计',
  'shuzijichengdianlushejiyuanli': '📚 数字集成电路设计原理',
  'shuziluojijichu_weidianzi': '📚 数字逻辑基础-微电子',
  'waiguojingjisichao': '📚 外国经济思潮',
  'xiandaishengwukexuedaolun': '📚 现代生物科学导论',
  'xinhaoyutongxinxitong': '📚 信号与通信系统',
  'zhiwugaibianshenghuo': '📚 植物改变生活',
  'zhongguoyinyueshi': '📚 中国音乐史',
  'zhongwaiyinyueshenmei': '📚 中外音乐审美',
  'xianqinzhexue': '📚 先秦哲学',
  'yingshijuyishu': '🎬 影视剧艺术',
}
